# Basic
title: å§šå…ˆç”Ÿ
subtitle: ä¸ªäººæ—¥è®°ç«™
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººæ—¥è®°å°ç«™ç«™~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: sir
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: ä¸€ä½æ²¡æœ‰å‹çš„å‹ç”·
url: ""

# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
enableToc: true

# Comment
comment:
    # disqus: liu
    duoshuo: liu

# Social
social:
    weibo: 13662019881
    github: killer-yao
    twitter: 571358216@qq.com
    mail: 571358216@qq.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f756121  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-84133259-6 
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge
textColor: #f06000
# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: æ—¥è®°ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ—¥è®°, description: archive, url: '/archive'}   
#- {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


